--
-- Table structure for table `role`
--

DROP TABLE role IF EXISTS;
CREATE TABLE role (
  id NUMERIC(11) GENERATED BY DEFAULT AS IDENTITY(START WITH 0, INCREMENT BY 1) PRIMARY KEY NOT NULL,
  name varchar(45) DEFAULT NULL);

--
-- Dumping data for table role
--
--INSERT INTO role VALUES (1,'ROLE_USER');
--
-- Table structure for table user
--

DROP TABLE user IF EXISTS;
CREATE TABLE user (
  id NUMERIC(11) GENERATED BY DEFAULT AS IDENTITY(START WITH 0, INCREMENT BY 4) PRIMARY KEY NOT NULL,
  username varchar(255) DEFAULT NULL,
  password varchar(255) DEFAULT NULL
);

--
-- Table structure for table user_role
--

DROP TABLE user_role IF EXISTS;
CREATE TABLE user_role (
  user_id NUMERIC(11) NOT NULL,
  role_id NUMERIC(11) NOT NULL,
  PRIMARY KEY (user_id,role_id), 
  CONSTRAINT fk_user_role_roleid FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_user_role_userid FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE ON UPDATE CASCADE
 );

CREATE INDEX fk_user_role_roleid_idx ON user_role (user_id);