create table role (id bigint generated by default as identity (start with 1), name varchar(255), primary key (id))
create table user (id bigint generated by default as identity (start with 1), password varchar(255), username varchar(255), primary key (id))
create table user_role (user_id bigint not null, role_id bigint not null, primary key (user_id, role_id))
alter table user_role add constraint FK_it77eq964jhfqtu54081ebtio foreign key (role_id) references role
alter table user_role add constraint FK_apcc8lxk2xnug8377fatvbn04 foreign key (user_id) references user
